Ft resources page 161791989
CodeForAfricaLabs/sensors.AFRICA-SeaSensors pull request #9
Opened 2019-01-17 18:07 UTC by puritybirir

##### What does this PR do?
- Create the Desktop_Resources Page in the Resources utilizing the Mobile Resources and the Desktop_Resources mockup on Zeplin

##### Description of Task to be completed?
 - Create The Resources Page
 - Create The Cards Component
 - Add get involved Component
 - Add Footer Component

##### Any background context you want to provide?
- None

##### What are the relevant Pivotal Tracker stories?
#161791989

##### Questions?
- None

##### Screenshots?
![resourcespage](https://user-images.githubusercontent.com/19901599/51338790-d22e1800-1a9b-11e9-915d-f71ccb6ae95d.gif)

2019-01-18 06:09 UTC, kilemensi commented
Hey @puritybirir. I think there is a bad/incomplete merge on this PR.

2019-01-22 09:39 UTC, kilemensi requested changes
Hey @puritybirir. Solid progress so far.

Lets fix a few obvious UX & code issues and I think we'll be very close to an MVP.

UX
==

Please go through the design again and try to match it as much as you can. Some obvious stuff I could pick up by just looking:

 + Broken components,

![screenshot from 2019-01-22 12-03-45](https://user-images.githubusercontent.com/1779590/51524196-94841300-1e3e-11e9-97b5-ac11bbe476a7.png)

 + Misaligned carousel tabs,

![screenshot from 2019-01-22 12-03-31](https://user-images.githubusercontent.com/1779590/51524209-9f3ea800-1e3e-11e9-9b06-41bfc439e0b9.png)

 + Needs more room between logo and hero.

![screenshot from 2019-01-22 12-05-44](https://user-images.githubusercontent.com/1779590/51524274-c39a8480-1e3e-11e9-8667-8a9ca9f7b143.png)

 + Too much space between the story cards or the story cards need to be wider,
 + All text content has the same width from the top of the page to the footer. If you look at the main headers in the design you'll see they start at the same left margin. In your implementation this vertical rhythm is lost, and
 + etc.

Code
====

 + Lets keep only two folder structure: `components` and `pages`. No need for reusable components folder, etc.
 + _Single_ file components do not need folders. It's fine to just use that file. Case in point, `More` should just be `components/More.js` and not `components/More/index.js`. The folder adds no value.
 + _Multiple_ file components *must* have their own folders. Case in point, `Blast`, it is correctly in `components/Blasts/index.js` since it's implementation also relies on `components/Blasts/blastSvg.js`
 + Page specific components may include the page name in their name _if/when_ there is a clash in names. So `AboutHeader` and `IndexHeader` are just two header components for the about and index pages respectively. But *all* components, page components or not, still must follow the above rules. For example in our code we have `IndexHeaderText` and `IndexHeaderCarousel`. If these components mean what they should, it means they're only for the index page header. This means they can all move into `IndexHeader` components as `components/IndexHeader/Text.js` and `components/IndexHeader/Carousel` with the main file being `components/IndexHeader/index.js`.
 + Use of headers like `h1` directly means we're not taking advantage of any typographical scaling/design provided by Material UI. We should really use material ui more (including theme support).

2019-01-22 09:39 UTC, kilemensi commented on package.json
> +    "add": "^2.0.6",
Do we really need this package? And with Material UI and `@mdi` already included, do we also need `bootstrap-css-only` below?

2019-01-22 09:39 UTC, kilemensi commented on package.json
> +    "yarn": "^1.13.0"
Is `yarn` really a runtime dependency?

2019-01-22 09:39 UTC, kilemensi commented on src/components/AboutImportantHeader/index.js
> +        <div>
What are these extra `<div>`s for?

2019-01-22 09:39 UTC, kilemensi commented on src/components/AboutUsHeader/index.js
> +      className={classes}
I don't think `className` is meant to be used like this... I know it works but I'd rather you create a different property like `classes` and use that to pass these classes.

2019-01-22 09:39 UTC, kilemensi commented on src/components/IndexNav/index.js
> +    <Link to={to} className={customClass}>{linkText}</Link>
React supports `children` property that you could have used here
```javascript
const function ListLink({ listItemClassName, to, linkClassName, children }) {
  <li className={listItemClassName}>
    <Link to={to} className={linkClassName}>{children}</Link>
```

And the usage will be:
```javascript
<ListLink to="/" listClass={classes.firstChild}>{image}</ListLink>
```

2019-01-22 09:39 UTC, kilemensi commented on src/components/ResourceCards/index.js
> +          <CssBaseline />
`CssBaseline` is already included in all pages using `withRoot`

2019-01-24 13:12 UTC, puritybirir commented on package.json
> +    "add": "^2.0.6",
Bootstrap css only is needed for the mdbreact carousel. After the MVP I think I will have to rebuild the whole carousel from scratch and stop using a library as it has proved to be extensively problematic

2019-01-24 13:39 UTC, puritybirir commented on src/components/IndexNav/index.js
> +    <Link to={to} className={customClass}>{linkText}</Link>
Done

2019-01-28 06:58 UTC, merged